### ISSUE TITLE
no distance measurement

### ISSUE THREAD

**Issue by n1kDon** [Resinchem/ESP-Parking-Assistant#11]
Hi thank you for your great project. I have a test build with a wemos d1 mini but the led strip is not leaving stand by mode. I tested changing the parking distances but no difference. In mqtt there is always "cardetected = 0", "parkdistance = 5080.0" . I tested my tfmini-s with another esp32 and that code (https://github.com/ibrahimqazi/TFmini-S-interfacing-with-ESP32) and I get good readings. How can I debug it and check if the tfmini is detected?

**Comment by Resinchem** [comment]
The parkdistance of 5080 means that the sensor is not returning a valid reading.  Are you running the latest version of the firmware?  Earlier versions did have an issue with the latest revision of the TFMini-s, but that has been fixed starting with release 0.40.  If you have a TFMini-s with a board number of v1.8.1 and are running a version of the firmware prior to 0.40, you won't get a distance reading (see the [0.40 Release Notes](https://github.com/Resinchem/ESP-Parking-Assistant/releases/tag/v0.40) for details).

Have you followed the [troubleshooting steps](https://github.com/Resinchem/ESP-Parking-Assistant/wiki/10-Troubleshooting) list in the wiki?  The latest firmware has been confirmed to work with the current version of the TFMini-s by multiple people, so I don't believe this is a firmware issue.

**Comment by n1kDon** [comment]
So I changed anything including the esp and no luck. So I remembered that I had a similar problem with tx/rx on another project and I found an old wemos d1 mini and now its working. I think there is a problem with some batches of the V 3.0 version of the "wemos" d1 mini. Thank you for your help.

**Comment by Resinchem** [comment]
Great!  Glad you got it working.  Thanks for posting the follow-up, as I was not aware of the issue with some D1 Minis, and maybe this can help someone else.  And thanks for closing the issue as resolved.
