### ISSUE TITLE
change minimum detection to 0.1m instead of 0.3m

### ISSUE THREAD

**Issue by n1kDon** [Resinchem/ESP-Parking-Assistant#12]
The minimum detection range of the TFMini-S is 0.1m not 0.3m, I tested it with TFMini-S version 1.81. 
See https://cdn.sparkfun.com/assets/8/a/f/a/c/16977-TFMini-S_-_Micro_LiDAR_Module-Product_Manual.pdf 
page 7. Perhaps you could consider changing that and add a disclaimer that you are not responsible for any damage on the car :)

**Comment by Resinchem** [comment]
I will double-check, but I believe the original TFMini-s v1.4 might have had a minimum distance of 300 mm and anything closer than that range still reported as 300 mm.  Seems like that is also what I remember from my testing.. but I do need to verify that.

If that is the case, I likely will not modify the existing firmware for shorter distances.. "disclaimer" or no disclaimer.  If someone has the older version and sets a minimum distance less than the sensor can measure, then they very easily could continue to pull forward, while the sensor is still showing they are 300 mm away.  Of course, you are welcome to modify your own source code and set the minimum distance to anything you want.

**Comment by Resinchem** [comment]
Testing has confirmed what I recalled.  While the newer v1.8.1 boards can report shorter distances, I found that the accuracy and stability begins to suffer at less than about 6".  I even got some readings that were less than 1", but they were very unstable and the next reading at the same distance might return something line 2".  Based on that alone, I might consider lowering the minimum distance to 6".

However, with the older v1.4 version, this was not the case.  I confirmed that anything shorter than 11.8" (the published minimum of 300mm), just continued to return 11.8".  This value was consistent whether the true distance was 4", 6," 8" or 10"....  it always returned 11.8".

For this reason, and to avoid maintaining separate versions for the different sensors, I am not going to lower the minimum distance at this time.  However, if you wish to do so yourself (and completely at your own risk), the minimum distance is only enforced on the web settings page.  You can simply take the source code and modify the 'min' value for each of the distance input fields to change the allowable minimum distance values for the system.
