### ISSUE TITLE
LEDs will not respond

### ISSUE THREAD

**Issue by balucanb** [Resinchem/ESP-Parking-Assistant#14]
So I followed @Resinchem video, instructions used the items from his list to build the board, Board powers, may not be an issue but the board led only flashes once on boot and does not remain on, but the software flashed fine, I can see the tf mini is powered as I see the red lights inside it, I am connected to my wifi even though the SSID is long ( im-under-your-bed) I see the parkasst on my network, I can go to the set up page and get no errors when saving options, I have tested and they are getting 5v. But not matter what I do I can not get any leds ( Im using 30 leds) to work? Any clue what may be going on and or any help is appreciated. Iattached pic of the board if that helps
![PXL_20230102_195942915](https://user-images.githubusercontent.com/34525580/210274381-fd955699-5ff8-4e1f-999a-78054b73bd8a.jpg)
![PXL_20230102_200020800](https://user-images.githubusercontent.com/34525580/210274384-40932655-a305-48a3-8f1c-6201b05bbd55.jpg)

**Comment by Resinchem** [comment]
If you are getting to the settings page and are able to save the settings... and can see the parking assistant device on your network, then everything is fine with the firmware.  Have you tried following the [troubleshooting steps](https://github.com/Resinchem/ESP-Parking-Assistant/wiki/10-Troubleshooting) as shown in the wiki?  There is a whole section about the LEDs not responding.  

But in short, if you are reaching the web settings page, it is generally one of two things... the LED strip is not wired correctly (or not getting a good signal) or the distance sensor is not returning a valid distance reading.  If you are not seeing the boot sequence on the LEDs, then it is likely the LED wiring.  If you see the LED boot sequence but then the LEDs do not come on after that, it is probably the distance sensor. 

Also, please assure you are running the latest release of the firmware.  Early versions did have issue with the new versions of the TFMini board, but this has been resolved.

**Comment by balucanb** [comment]
Leaving this here for anyone else that might have the same issue. CHECK your connections, then check them again..and one more time! After pulling out the multimeter there was 1 solder joint that appeared to be good be view but it wasn't. After a quick addition of a little solder ALL was good. :)
