### ISSUE TITLE
Pins for HC-SR04 without logic level shifter

### ISSUE THREAD

**Issue by LuxStatera** [Resinchem/ESP-Parking-Assistant#19]
I have a D1 Mini, LED strip and HC-SR04. I want to make sure I am using the correct pins on the D1 Mini. What pins would you recommend without the logic level shifter? Will everything still work without it?

**Comment by Resinchem** [comment]
**This code will not work with the HC-SR04... period.**  The code would have to be substantially modified with different libraries to read the distances from the HC-SR04.   This code will ONLY work with the TF-Mini.  Wiring will not matter.

If you want to use the HC-SR04, I suggest you look at one of the forks of this project that have been rewritten to work with the HC-SR04 and post your wiring questions there as I am not the one supporting those versions.

But I will say that you _might_ get away without the logic level shifter if you keep the controller close to the start of the LED strip.  You may be fine... and you may not if the voltage on the data line drops too low.  This will lead to flickering and other misbehaving of the LEDs.  But you are obviously free to roll the dice and take your chances.  I would highly recommend a bench test with the expected wiring lead length of your final install before creating any final version.
