### ISSUE TITLE
MQTT message after LED change

### ISSUE THREAD

**Issue by n1kDon** [Resinchem/ESP-Parking-Assistant#20]
Hi, thanks for the great project. Its working great, but now to my issue. I bought an old traffic light and wanted to sync it with the parking assistant. I changed the code for my needs but when I compile the esp8266 (d1 mini) is behaving very slow with slow led and website response, **even when I test compile with the original source code**. Tried with different arduino ide and library versions but had no luck. Setting MQTT off for testing doesn't change the behavior. The precompiled version is working normal. 
I changed only the Update LEDs part and inserted a new global variable.

```cpp
// Global variable
String prevLEDStatus = "";

// Update LEDs
if ((carDetected) && (isAwake)) {
    String currentLEDStatus = "";  // Variable to store the current LED status

    if (tf_dist <= backupDistance) {
        // Beyond minimum distance - flash backup!
        blinkLEDs(ledColorBackup);
        currentLEDStatus = "backup";

    } else if (tf_dist <= parkDistance) {  
        // In desired parked distance
        fill_solid(LEDs, numLEDs, ledColorParked);
        currentLEDStatus = "parked";

    } else if ((tf_dist > startDistance) && (tf_dist <= wakeDistance)) {
        // Beyond start distance but within wake distance
        fill_solid(LEDs, numLEDs, ledColorWake);
        currentLEDStatus = "wake";

    } else if ((tf_dist <= startDistance) && (tf_dist > parkDistance)) {
        // Update based on selected effect
        if (ledEffect_m1 == "Out-In") {
            updateOutIn(tf_dist);
        } else if (ledEffect_m1 == "In-Out") {
            updateInOut(tf_dist);
        } else if (ledEffect_m1 == "Full-Strip") {
            updateFullStrip(tf_dist);
        } else if (ledEffect_m1 == "Full-Strip-Inv") {
            updateFullStripInv(tf_dist);
        } else if (ledEffect_m1 == "Solid") {
            updateSolid(tf_dist);
        }
        currentLEDStatus = "start";
    }

    // Check if the LED status has changed
    if (currentLEDStatus != prevLEDStatus) {
        // If the MQTT client is connected, publish the LED status
        if (client.connected()) {
            String topic = "parkingAssistant/" + mqttTopicPub + "/led_status";
            client.publish(topic.c_str(), currentLEDStatus.c_str());
        }
        // Update the previous LED status with the current status
        prevLEDStatus = currentLEDStatus;
    }
}
```
Has anyone else faced a similar issue or have any insights on what might be causing the slowdown? Any help would be greatly appreciated.

Thank you!

**Comment by Resinchem** [comment]
I am by no means an expert when it comes to Arduino, libraries or other detailed options when it comes to creating compiled code.  However, if the precompiled version runs fine and your compiled version is sluggish or isn't working quite right, then it would seem that there is obviously something different in our two environments when compilation occurs.  This may or may not be helpful, but here are the related versions and options I used for the original version:  

Arduino IDE 1.8.16
ESP8266 Board 2.7.4

Applicable Library Versions:

WiFiManager.h  2.0.8-beta
FastLED 3.5.0
ArduinoJson 6.18.5
TFMPlus 1.5.0
PubSubClient 2.8.0

![image](https://github.com/Resinchem/ESP-Parking-Assistant/assets/55962781/1fde9dea-8313-47d8-9ed0-6f8395c49e3d)

I don't know if any of that will be helpful or not, but that's about the only thing I can think of if the precompiled bin is fine, but when you compile your own (even with the original source), the response is sluggish.

**Comment by n1kDon** [comment]
Thank you for your assistance. The issue has been resolved. Here's what I did:

Downgraded some of the libraries to the versions you used and switched my board from a d1mini clone to the D1 R2 & mini.
With these changes, everything is working smoothly. I can now proceed to test and refine my MQTT setup further.

**Comment by Resinchem** [comment]
Great.. glad that resolved it.  I'm going to go ahead and mark as 'resolved' and close the issue.
