### ISSUE TITLE
Support HC-SR04

### ISSUE THREAD

**Issue by renat2985** [Resinchem/ESP-Parking-Assistant#8]
I understand that this sensor is worse. But I would still really like to see support for this module in your firmware.
Thanks.

**Comment by Resinchem** [comment]
I understand the desire to use the lower cost HC-SR04, but it is not something I currently have the time to develop and support.  It would mean maintaining and updating two different versions of the firmware every time I wanted to make a change or improvement.  However, you or anyone else is free to clone or fork the code and replace the TFMini with the HC-SR04.  It would really just involve removing the TFMini library and related references and changing the distance measuring procedure to get a reading from the HC-SR04 using two GPIO pins.  As long as the code in the main loop is getting a distance reading in mm, it really doesn't care where it comes from... and all the rest of the application, including the LED logic, the web app, OTA updates, etc. should work as-is.

I may consider making an HC-SR04 version available at some point in time, but I certainly am not able to do so at the current time with my existing project load.  So, for now, I'm going to close the issue and mark it as 'won't fix'.  If I time comes that I am able to create a separate version, I will reinstate or recreate the enhancement request.
