### ISSUE TITLE
Link from blog post incorrect

### ISSUE THREAD

**Issue by withanhdammit** [Resinchem/ESP-Parking-Assistant#9]
The link on the blog post to the wiki has an extraneous space in it.

The link is:
https://github.com/Resinchem/ESP-Parking-Assistant /wiki
(https://github.com/Resinchem/ESP-Parking-Assistant%20/wiki when viewed in the browser address bar)

And should be:
https://github.com/Resinchem/ESP-Parking-Assistant/wiki

**Comment by Resinchem** [comment]
Thanks for the catch.  This has been fixed.
